### PR TITLE
user login and signing authentication

### PR DESCRIPTION
**Pull request by iyiola-dev**
i created the user login and sign in authentication .. in the sign in page there is an signin anon there for users that want to sign in without logging in... i think we discussed about this

### CODE REVIEW

**Comment by Mastersam07** [comment]
info • 'hasFloatingPlaceholder' is deprecated and shouldn't be used. Use floatingLabelBehaviour instead. This feature was deprecated after v1.13.2. • lib/Views/login_view.dart:45:29 • deprecated_member_use
   info • 'hasFloatingPlaceholder' is deprecated and shouldn't be used. Use floatingLabelBehaviour instead. This feature was deprecated after v1.13.2. • lib/Views/register_view.dart:45:29 • deprecated_member_use

@iyiola-dev

**Comment by iyiola-dev** [comment]
okay will do

**Comment by Mastersam07** [comment]
Ensure to always format your code before committing. Your code failed the format test....

**Review by Mastersam07 — APPROVED** [review]
Ensure to always format your code before committing. Your code failed the format test.... However, i will merge this as it breaks nothing

**Pull request merged**
